Update gn from chromium source
url=https://chromium.googlesource.com/chromium/src.git
gitrev=002c7e3c592d90535914a103c8736a74b0d04d2f
svnrev=363783

diff --git a/build/android/adb_gdb b/build/android/adb_gdb
--- a/build/android/adb_gdb
+++ b/build/android/adb_gdb
@@ -691,7 +691,7 @@ if [ "$START" ]; then
 package is installed?"
 fi
 
-# Return the timestamp of a given time, as number of seconds since epoch.
+# Return the timestamp of a given file, as number of seconds since epoch.
 # $1: file path
 # Out: file timestamp
 get_file_timestamp () {
@@ -707,12 +707,14 @@ get_file_timestamp () {
 #
 detect_symbol_dir () {
   local SUBDIRS SUBDIR LIST DIR DIR_LIBS TSTAMP
-  # Note: Ninja places debug libraries under out/$BUILDTYPE/lib/, while
-  # Make places then under out/$BUILDTYPE/lib.target.
+  # Make places them under out/$BUILDTYPE/lib.target.
+  # GYP places debug libraries under out/$BUILDTYPE/lib
+  # GN places them under out/$BUILDTYPE/lib.unstripped
   if [ "$1" ]; then
-    SUBDIRS="$1/lib $1/lib.target"
+    SUBDIRS="$1/lib $1/lib.target $1/lib.unstripped"
   else
     SUBDIRS="Release/lib Debug/lib Release/lib.target Debug/lib.target"
+    SUBDIRS+=" Release/lib.unstripped Debug/lib.unstripped"
   fi
   LIST=$TMPDIR/scan-subdirs-$$.txt
   printf "" > "$LIST"
@@ -767,6 +769,7 @@ PULL_LIBS_DIR=${PULL_LIBS_DIR:-$DEFAULT_PULL_LIBS_DIR}
 
 HOST_FINGERPRINT=
 DEVICE_FINGERPRINT=$(adb_shell getprop ro.build.fingerprint)
+[[ "$DEVICE_FINGERPRINT" ]] || panic "Failed to get the device fingerprint"
 log "Device build fingerprint: $DEVICE_FINGERPRINT"
 
 # If --pull-libs-dir is not specified, and this is a platform build, look
@@ -794,11 +797,11 @@ fi
 # fingerprints of the device, and the cached system libraries on the host.
 #
 if [ -z "$NO_PULL_LIBS" -a -z "$PULL_LIBS" ]; then
-  if [ ! -f "$PULL_LIBS_DIR/build.prop" ]; then
+  if [ ! -f "$PULL_LIBS_DIR/build.fingerprint" ]; then
     log "Auto-config: --pull-libs  (no cached libraries)"
     PULL_LIBS=true
   else
-    HOST_FINGERPRINT=$(get_build_fingerprint_from "$PULL_LIBS_DIR/build.prop")
+    HOST_FINGERPRINT=$(< "$PULL_LIBS_DIR/build.fingerprint")
     log "Host build fingerprint:   $HOST_FINGERPRINT"
     if [ "$HOST_FINGERPRINT" == "$DEVICE_FINGERPRINT" ]; then
       log "Auto-config: --no-pull-libs (fingerprint match)"
@@ -897,7 +900,6 @@ log "Command suffix: '$COMMAND_SUFFIX'"
 # we need by looking at /proc/$PID/maps instead
 if [ "$PULL_LIBS" -a -z "$NO_PULL_LIBS" ]; then
   echo "Extracting system libraries into: $PULL_LIBS_DIR"
-  rm -f $PULL_LIBS_DIR/build.prop
   MAPPINGS=$(adb_shell $COMMAND_PREFIX cat /proc/$PID/maps $COMMAND_SUFFIX)
   if [ $? != 0 ]; then
     echo "ERROR: Could not list process's memory mappings."
@@ -907,6 +909,8 @@ if [ "$PULL_LIBS" -a -z "$NO_PULL_LIBS" ]; then
       panic "Use --su-prefix if the application is not debuggable."
     fi
   fi
+  # Remove the fingerprint file in case pulling one of the libs fails.
+  rm -f "$PULL_LIBS_DIR/build.fingerprint"
   SYSTEM_LIBS=$(echo "$MAPPINGS" | \
       awk '$6 ~ /\/system\/.*\.so$/ { print $6; }' | sort -u)
   for SYSLIB in /system/bin/linker $SYSTEM_LIBS; do
@@ -916,9 +920,8 @@ if [ "$PULL_LIBS" -a -z "$NO_PULL_LIBS" ]; then
     mkdir -p "$DST_DIR" && adb pull $SYSLIB "$DST_FILE" 2>/dev/null
     fail_panic "Could not pull $SYSLIB from device !?"
   done
-  echo "Pulling device build.prop"
-  adb pull /system/build.prop $PULL_LIBS_DIR/build.prop
-  fail_panic "Could not pull device build.prop !?"
+  echo "Writing the device fingerprint"
+  echo "$DEVICE_FINGERPRINT" > "$PULL_LIBS_DIR/build.fingerprint"
 fi
 
 # Find all the sub-directories of $PULL_LIBS_DIR, up to depth 4
@@ -946,10 +949,16 @@ TARGET_PORT=$PORT
 
 # Select correct app_process for architecture.
 case $TARGET_ARCH in
-      arm|x86|mips) GDBEXEC=app_process;;
+      arm|x86|mips) GDBEXEC=app_process32;;
       arm64|x86_64) GDBEXEC=app_process64;;
       *) fail_panic "Unknown app_process for architecture!";;
 esac
+
+# Default to app_process if bit-width specific process isn't found.
+adb_shell ls /system/bin/$GDBEXEC
+if [ $? != 0 ]; then
+    GDBEXEC=app_process
+fi
 
 # Detect AddressSanitizer setup on the device. In that case app_process is a
 # script, and the real executable is app_process.real.
@@ -980,9 +989,9 @@ host:localhost:$HOST_PORT to device:localhost:$TARGET_PORT!"
 log "Starting gdbserver in the background:"
 GDBSERVER_LOG=$TMPDIR/gdbserver-$TMP_ID.log
 log "adb shell $COMMAND_PREFIX $TARGET_GDBSERVER :$TARGET_PORT \
---attach $PID $COMMAND_SUFFIX"
-("$ADB" shell $COMMAND_PREFIX $TARGET_GDBSERVER :$TARGET_PORT \
- --attach $PID $COMMAND_SUFFIX > $GDBSERVER_LOG 2>&1) &
+  --attach $PID $COMMAND_SUFFIX"
+"$ADB" shell $COMMAND_PREFIX $TARGET_GDBSERVER :$TARGET_PORT \
+  --attach $PID $COMMAND_SUFFIX > $GDBSERVER_LOG 2>&1 &
 GDBSERVER_PID=$!
 echo "$GDBSERVER_PID" > $GDBSERVER_PIDFILE
 log "background job pid: $GDBSERVER_PID"
